CONFIG_ZMK_BLE=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

CONFIG_SPI=y
CONFIG_INPUT=y

CONFIG_PMW3610_ALT=y
CONFIG_PMW3610_ALT_REPORT_INTERVAL_MIN=16
CONFIG_PMW3610_ALT_INIT_POWER_UP_EXTRA_DELAY_MS=300
CONFIG_PMW3610_ALT_RUN_DOWNSHIFT_TIME_MS=3264

CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y
CONFIG_ZMK_NON_LIPO_MIN_MV=352
CONFIG_ZMK_NON_LIPO_MAX_MV=448
CONFIG_ZMK_NON_LIPO_LOW_MV=0
CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_EXT_POWER=y
