CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_BLE=y

CONFIG_MAIN_STACK_SIZE=4096
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_SPI=y
CONFIG_INPUT=y
CONFIG_ZMK_INPUT_PROCESSORS=y

CONFIG_XY_CLIPPER=y
CONFIG_ZMK_INPUT_PROCESSOR_XY_CLIPPER=y

CONFIG_ZMK_NON_LIPO_BATTERY_MANAGEMENT=y
CONFIG_ZMK_NON_LIPO_MIN_MV=352
CONFIG_ZMK_NON_LIPO_MAX_MV=448
CONFIG_ZMK_NON_LIPO_LOW_MV=0

CONFIG_ZMK_BATTERY_REPORTING=y

CONFIG_ZMK_BLE_PASSKEY_ENTRY=n
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

CONFIG_ZMK_EXT_POWER=y
