include:
  - board: xiao_ble/nrf52840/zmk
    shield: hitsuki46_R
    artifact-name: hitsuki46_R
  - board: xiao_ble/nrf52840/zmk
    shield: hitsuki46_L
    artifact-name: hitsuki46_L
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset
    artifact-name: settings_reset
