include:
  - board: xiao_ble//zmk
    shield: hitsuki46_R
    snippet: studio-rpc-usb-uart
    artifact-name: hitsuki46_R

  - board: xiao_ble//zmk
    shield: hitsuki46_L
    artifact-name: hitsuki46_L

  - board: xiao_ble//zmk
    shield: settings_reset
    artifact-name: settings_reset
